services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: gestao
      POSTGRES_PASSWORD: gestao
      POSTGRES_DB: gestao_estoque
    ports:
      - "5432:5432"
    volumes:
      - gestao_pgdata:/var/lib/postgresql/data

volumes:
  gestao_pgdata:
